name: 'ReviewPal'
description: 'Help humans review AI-generated code faster with comprehension aids'
author: 'Han Kim'

branding:
  icon: 'eye'
  color: 'purple'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude analysis (optional - static analysis works without it)'
    required: false
  github_token:
    description: 'GitHub token for posting comments (defaults to GITHUB_TOKEN)'
    required: false
    default: ${{ github.token }}
  model:
    description: 'Claude model to use (if API key provided)'
    required: false
    default: 'claude-sonnet-4-20250514'
  max_hunks:
    description: 'Maximum number of hunks to analyze'
    required: false
    default: '20'
  skip_summary:
    description: 'Skip "What Changed & Why" analysis (requires API)'
    required: false
    default: 'false'
  skip_patterns:
    description: 'Skip Claude pattern detection (static React patterns still run)'
    required: false
    default: 'false'
  skip_complexity:
    description: 'Skip complexity analysis'
    required: false
    default: 'false'
  comment_on_pr:
    description: 'Post analysis as PR comment'
    required: false
    default: 'true'
  inline_comments:
    description: 'Post inline comments on specific lines'
    required: false
    default: 'true'
  max_inline_comments:
    description: 'Maximum inline comments to post (prevents spam)'
    required: false
    default: '10'
  fail_on_high_complexity:
    description: 'Fail workflow if high complexity detected'
    required: false
    default: 'false'
  format:
    description: 'Output format: friendly, markdown, json, text'
    required: false
    default: 'friendly'

outputs:
  total_files:
    description: 'Number of files analyzed'
  total_hunks:
    description: 'Number of hunks reviewed'
  ai_likelihood:
    description: 'Overall AI code likelihood (low/medium/high)'
  patterns_found:
    description: 'Number of patterns detected'
  high_complexity_hunks:
    description: 'Number of high-complexity hunks'
  analysis_markdown:
    description: 'Full analysis in markdown format'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm ci --production
    
    - name: Build
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm run build
    
    - name: Get PR diff
      shell: bash
      id: diff
      run: |
        git fetch origin ${{ github.base_ref }} --depth=1
        git diff origin/${{ github.base_ref }}...HEAD > /tmp/pr.diff
        echo "diff_file=/tmp/pr.diff" >> $GITHUB_OUTPUT
        echo "lines=$(wc -l < /tmp/pr.diff)" >> $GITHUB_OUTPUT
    
    - name: Skip if no diff
      if: steps.diff.outputs.lines == '0'
      shell: bash
      run: |
        echo "No changes detected, skipping analysis"
        echo "total_files=0" >> $GITHUB_OUTPUT
        echo "total_hunks=0" >> $GITHUB_OUTPUT
        exit 0
    
    - name: Run analysis
      shell: bash
      id: analyze
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
      run: |
        cd ${{ github.action_path }}
        
        # Build options
        OPTIONS=""
        if [ "${{ inputs.skip_summary }}" = "true" ] || [ -z "${{ inputs.anthropic_api_key }}" ]; then
          OPTIONS="$OPTIONS --no-summary"
        fi
        if [ "${{ inputs.skip_patterns }}" = "true" ]; then
          OPTIONS="$OPTIONS --no-patterns"
        fi
        if [ "${{ inputs.skip_complexity }}" = "true" ]; then
          OPTIONS="$OPTIONS --no-complexity"
        fi
        
        # Run analysis with friendly format
        node dist/index.js ${{ steps.diff.outputs.diff_file }} \
          --format ${{ inputs.format }} \
          --max-hunks ${{ inputs.max_hunks }} \
          --model ${{ inputs.model }} \
          $OPTIONS > /tmp/analysis.md 2>&1 || true
        
        # Export for outputs
        echo "analysis_markdown<<EOF" >> $GITHUB_OUTPUT
        cat /tmp/analysis.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        # Also run JSON for structured data
        node dist/index.js ${{ steps.diff.outputs.diff_file }} \
          --format json \
          --max-hunks ${{ inputs.max_hunks }} \
          --model ${{ inputs.model }} \
          $OPTIONS > /tmp/analysis.json 2>&1 || echo '{"files":[],"totalHunks":0,"aiCodeLikelihood":"low"}' > /tmp/analysis.json
        
        # Extract key metrics safely
        echo "total_files=$(jq '.files | length // 0' /tmp/analysis.json)" >> $GITHUB_OUTPUT
        echo "total_hunks=$(jq '.totalHunks // 0' /tmp/analysis.json)" >> $GITHUB_OUTPUT
        echo "ai_likelihood=$(jq -r '.aiCodeLikelihood // "low"' /tmp/analysis.json)" >> $GITHUB_OUTPUT
    
    - name: Post PR comment
      if: inputs.comment_on_pr == 'true' && github.event_name == 'pull_request' && steps.analyze.outputs.total_hunks != '0'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const analysis = `${{ steps.analyze.outputs.analysis_markdown }}`;
          const marker = '<!-- reviewpal -->';
          
          // Skip if no meaningful content
          if (!analysis.trim() || analysis.includes('No major concerns found')) {
            console.log('No issues found, skipping comment');
            return;
          }
          
          // Find existing comment from this action
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });
          
          const botComment = comments.find(c => 
            c.body && c.body.includes(marker)
          );
          
          const body = `${marker}\n\n${analysis}`;
          
          if (botComment) {
            // Update existing comment
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body
            });
            console.log('Updated existing comment');
          } else {
            // Create new comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
            console.log('Created new comment');
          }
    
    - name: Check complexity threshold
      if: inputs.fail_on_high_complexity == 'true'
      shell: bash
      run: |
        COMPLEXITY=$(jq '[.files[].hunks[].complexity.score // 0] | max // 0' /tmp/analysis.json)
        if (( $(echo "$COMPLEXITY > 7" | bc -l) )); then
          echo "::error::High complexity detected (score: $COMPLEXITY)"
          exit 1
        fi
